services:
  - type: web
    name: EsotericBot_2
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn bot:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
